version: '3'

services:
  fileserver:
    image: codeskyblue/gohttpserver
    container_name: gohttpserver
    restart: unless-stopped
    ports:
      - 7050:8000
    volumes:
      - ./data:/app/public
    command: --upload --delete
